# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/Documents/Biometria/FaRe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/Documents/Biometria/FaRe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Documents/Biometria/FaRe/CMakeFiles /root/Documents/Biometria/FaRe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Documents/Biometria/FaRe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FaRe

# Build rule for target.
FaRe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FaRe
.PHONY : FaRe

# fast build rule for target.
FaRe/fast:
	$(MAKE) -f CMakeFiles/FaRe.dir/build.make CMakeFiles/FaRe.dir/build
.PHONY : FaRe/fast

src/Graph.o: src/Graph.cpp.o

.PHONY : src/Graph.o

# target to build an object file
src/Graph.cpp.o:
	$(MAKE) -f CMakeFiles/FaRe.dir/build.make CMakeFiles/FaRe.dir/src/Graph.cpp.o
.PHONY : src/Graph.cpp.o

src/Graph.i: src/Graph.cpp.i

.PHONY : src/Graph.i

# target to preprocess a source file
src/Graph.cpp.i:
	$(MAKE) -f CMakeFiles/FaRe.dir/build.make CMakeFiles/FaRe.dir/src/Graph.cpp.i
.PHONY : src/Graph.cpp.i

src/Graph.s: src/Graph.cpp.s

.PHONY : src/Graph.s

# target to generate assembly for a file
src/Graph.cpp.s:
	$(MAKE) -f CMakeFiles/FaRe.dir/build.make CMakeFiles/FaRe.dir/src/Graph.cpp.s
.PHONY : src/Graph.cpp.s

src/PhotosContainer.o: src/PhotosContainer.cpp.o

.PHONY : src/PhotosContainer.o

# target to build an object file
src/PhotosContainer.cpp.o:
	$(MAKE) -f CMakeFiles/FaRe.dir/build.make CMakeFiles/FaRe.dir/src/PhotosContainer.cpp.o
.PHONY : src/PhotosContainer.cpp.o

src/PhotosContainer.i: src/PhotosContainer.cpp.i

.PHONY : src/PhotosContainer.i

# target to preprocess a source file
src/PhotosContainer.cpp.i:
	$(MAKE) -f CMakeFiles/FaRe.dir/build.make CMakeFiles/FaRe.dir/src/PhotosContainer.cpp.i
.PHONY : src/PhotosContainer.cpp.i

src/PhotosContainer.s: src/PhotosContainer.cpp.s

.PHONY : src/PhotosContainer.s

# target to generate assembly for a file
src/PhotosContainer.cpp.s:
	$(MAKE) -f CMakeFiles/FaRe.dir/build.make CMakeFiles/FaRe.dir/src/PhotosContainer.cpp.s
.PHONY : src/PhotosContainer.cpp.s

src/Program.o: src/Program.cpp.o

.PHONY : src/Program.o

# target to build an object file
src/Program.cpp.o:
	$(MAKE) -f CMakeFiles/FaRe.dir/build.make CMakeFiles/FaRe.dir/src/Program.cpp.o
.PHONY : src/Program.cpp.o

src/Program.i: src/Program.cpp.i

.PHONY : src/Program.i

# target to preprocess a source file
src/Program.cpp.i:
	$(MAKE) -f CMakeFiles/FaRe.dir/build.make CMakeFiles/FaRe.dir/src/Program.cpp.i
.PHONY : src/Program.cpp.i

src/Program.s: src/Program.cpp.s

.PHONY : src/Program.s

# target to generate assembly for a file
src/Program.cpp.s:
	$(MAKE) -f CMakeFiles/FaRe.dir/build.make CMakeFiles/FaRe.dir/src/Program.cpp.s
.PHONY : src/Program.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FaRe"
	@echo "... src/Graph.o"
	@echo "... src/Graph.i"
	@echo "... src/Graph.s"
	@echo "... src/PhotosContainer.o"
	@echo "... src/PhotosContainer.i"
	@echo "... src/PhotosContainer.s"
	@echo "... src/Program.o"
	@echo "... src/Program.i"
	@echo "... src/Program.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

